FROM mcr.microsoft.com/devcontainers/javascript-node:16-bullseye

# It doesn't make much sense to install nginx here in this container
# It is just an example how to install additional software here in the Dockerfile
# RUN apt-get update && apt-get install -y nginx

